### ISSUE TITLE
What is a thumbnail? 

### ISSUE THREAD

**Issue by Wizzel1** [aloisdeniel/media_gallery#17]
Hi, thanks for your awesome package. Really saves me a lot of time. 
However I don't quite understand what the `Future<List<int>>` that is returned by the `getThumbnail()` call represents.

**Comment by aloisdeniel** [comment]
Hi, thanks !

A thumbnail is a small image representing the media. The `List<int>` represents the bytes of that image.

To render it from a widget you can use `MediaThumbnailProvider `.
