### ISSUE TITLE
Media class should expose file path

### ISSUE THREAD

**Issue by jj-gh** [aloisdeniel/media_gallery#3]
to make sorting by file name or type possible without having to do a getFile().path

**Comment by aloisdeniel** [comment]
Unfortunately, files from the galleries aren't just pointers to files.

Even if on [Android](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DISPLAY_NAME) there's a display name property, images from [iOS](https://developer.apple.com/documentation/photokit/phasset) gallery don't have a name, but only an ID.

**Comment by jj-gh** [comment]
i see. that kinda sucks but thanks for the info.
