### ISSUE TITLE
Black thumbnail for video

### ISSUE THREAD

**Issue by danielwalczak** [aloisdeniel/media_gallery#5]
When I run example app or use the plugin, thumbnails for videos are black, no image.

**Comment by aloisdeniel** [comment]
Hello ! On which platform ?

**Comment by danielwalczak** [comment]
I solved issue with the video itself, but using your example on my iOS phone, while Im scrolling through list of videos app is crashing.

<img width="893" alt="Zrzut ekranu 2020-06-15 o 4 25 44 PM" src="https://user-images.githubusercontent.com/3720039/84715295-df676480-af24-11ea-89c3-382ba80b6c2b.png">
